Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcCoreTwoTwo.Data;
using MvcCoreTwoTwo.Models;
using MvcCoreTwoTwo.Repository;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MvcCoreTwoTwo.Controllers
{
    [Authorize]
    public class FeedbackController : Controller
    {
        private readonly IFeedbackRepository _feedbackRepository;
        public FeedbackController(IFeedbackRepository feedbackRepository)
        {
            _feedbackRepository = feedbackRepository;
        }
        // GET: /<controller>/
 
        public IActionResult CreateFeedback()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateFeedback(Feedback feedback)
        {
            if (!ModelState.IsValid)
                return View(feedback);

            _feedbackRepository.AddFeedback(feedback);
            return RedirectToAction("FeedbackCompleted");
        }

        public IActionResult FeedbackCompleted()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link rel="stylesheet" href="~/Content/site.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li> <a asp-controller="Home" asp-action="Index" class="navbar-brand">Shanaz Painting Gallery</a></li>
                    <li><a asp-controller="Feedback" asp-action="CreateFeedback">Feedback</a></li>
                    <li><a asp-controller="Admin" asp-action="AddPaint">Admin</a></li>
                    <partial name="_LoginPartial" />
                </ul> 
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>    
    </div>
    @RenderSection("Scripts", required:false)
</body>
</html>